<a href="https://colab.research.google.com/github/ttury/Deep-Learning-For-Natural-Language-Processing/blob/master/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)
print()

b = np.array([[11, 12], [21, 22], [31, 32]])
print(b)
print()

print(b.ndim)
print(b.shape)
print()

matrix_zeros = np.zeros((3, 3))
print(matrix_zeros)
print()

matrix_ones = np.ones((3, 3))
print(matrix_ones)
print()

matrix_eyes = np.eye(3)
print(matrix_eyes)
print()

matrix_random = np.random.random((3, 3))
print(matrix_random)
print()

matrix_arrange = np.arange(10, 91, 10)
print(matrix_arrange)
print()

matrix_reshape = np.array(np.arange(9)).reshape((3, 3))
print(matrix_reshape)
print()

matrix_sliced = np.array([[1, 2, 3], [4, 5, 6]])
matrix_slicing = matrix_sliced[0:2, 1:3]
matrix_slicing_row = matrix_sliced[0, :]
matrix_slicing_column = matrix_sliced[:, 0]
print(matrix_slicing)
print(matrix_slicing_row)
print(matrix_slicing_column)
print()

matrix_indexed = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
matrix_indexing = matrix_indexed[[0, 2], [1, 0]]
print(matrix_indexing)
print()

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print()

matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
matrix_dot = np.dot(matrix1, matrix2)
print(matrix_dot)

[1 2 3 4 5]

[[11 12]
 [21 22]
 [31 32]]

2
(3, 2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0.41558897 0.2806207  0.28398439]
 [0.71385557 0.15371651 0.19293766]
 [0.44049556 0.27275658 0.12580945]]

[10 20 30 40 50 60 70 80 90]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 3]
 [5 6]]
[1 2 3]
[1 4]

[12 31]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

[[19 22]
 [43 50]]
